//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace PubbliSelfHostedAPI.Service
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PrezzoMedio
    {

        private string kpiCommissionatoField;

        private string annoPrecedenteField;

        private string annoPrecedentePDField;

        private string annoCorrenteField;

        private string perCentAcPdField;

        private string budgetField;

        private string deltaField;

        private string perCentAcBdgField;

        private string annoField;

        private string meseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KpiCommissionato
        {
            get
            {
                return this.kpiCommissionatoField;
            }
            set
            {
                this.kpiCommissionatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnoPrecedente
        {
            get
            {
                return this.annoPrecedenteField;
            }
            set
            {
                this.annoPrecedenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnoPrecedentePD
        {
            get
            {
                return this.annoPrecedentePDField;
            }
            set
            {
                this.annoPrecedentePDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnoCorrente
        {
            get
            {
                return this.annoCorrenteField;
            }
            set
            {
                this.annoCorrenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PerCentAcPd
        {
            get
            {
                return this.perCentAcPdField;
            }
            set
            {
                this.perCentAcPdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Budget
        {
            get
            {
                return this.budgetField;
            }
            set
            {
                this.budgetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Delta
        {
            get
            {
                return this.deltaField;
            }
            set
            {
                this.deltaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PerCentAcBdg
        {
            get
            {
                return this.perCentAcBdgField;
            }
            set
            {
                this.perCentAcBdgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Anno
        {
            get
            {
                return this.annoField;
            }
            set
            {
                this.annoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mese
        {
            get
            {
                return this.meseField;
            }
            set
            {
                this.meseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Commissionato
    {

        private string kpiCommissionatoField;

        private string annoPrecedenteField;

        private string annoPrecedentePDField;

        private string annoCorrenteField;

        private string perCentAcPdField;

        private string budgetField;

        private string deltaField;

        private string perCentAcBdgField;

        private string annoField;

        private string meseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KpiCommissionato
        {
            get
            {
                return this.kpiCommissionatoField;
            }
            set
            {
                this.kpiCommissionatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnoPrecedente
        {
            get
            {
                return this.annoPrecedenteField;
            }
            set
            {
                this.annoPrecedenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnoPrecedentePD
        {
            get
            {
                return this.annoPrecedentePDField;
            }
            set
            {
                this.annoPrecedentePDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AnnoCorrente
        {
            get
            {
                return this.annoCorrenteField;
            }
            set
            {
                this.annoCorrenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PerCentAcPd
        {
            get
            {
                return this.perCentAcPdField;
            }
            set
            {
                this.perCentAcPdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Budget
        {
            get
            {
                return this.budgetField;
            }
            set
            {
                this.budgetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Delta
        {
            get
            {
                return this.deltaField;
            }
            set
            {
                this.deltaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PerCentAcBdg
        {
            get
            {
                return this.perCentAcBdgField;
            }
            set
            {
                this.perCentAcBdgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Anno
        {
            get
            {
                return this.annoField;
            }
            set
            {
                this.annoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mese
        {
            get
            {
                return this.meseField;
            }
            set
            {
                this.meseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class KPI
    {

        private string kpiExceptionField;

        private string totaleMovimentiByClientiField;

        private string totaleMovimentiByAgenzieField;

        private KPIClienti[] clientiField;

        private KPIAgenzie[] agenzieField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KpiException
        {
            get
            {
                return this.kpiExceptionField;
            }
            set
            {
                this.kpiExceptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotaleMovimentiByClienti
        {
            get
            {
                return this.totaleMovimentiByClientiField;
            }
            set
            {
                this.totaleMovimentiByClientiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TotaleMovimentiByAgenzie
        {
            get
            {
                return this.totaleMovimentiByAgenzieField;
            }
            set
            {
                this.totaleMovimentiByAgenzieField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Clienti", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KPIClienti[] Clienti
        {
            get
            {
                return this.clientiField;
            }
            set
            {
                this.clientiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Agenzie", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KPIAgenzie[] Agenzie
        {
            get
            {
                return this.agenzieField;
            }
            set
            {
                this.agenzieField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class KPIClienti
    {

        private string descrizioneCommissionatoField;

        private string descrizionePrezzoMedioField;

        private PrezzoMedio[] prezzoMedioField;

        private Commissionato[] commissionatoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DescrizioneCommissionato
        {
            get
            {
                return this.descrizioneCommissionatoField;
            }
            set
            {
                this.descrizioneCommissionatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DescrizionePrezzoMedio
        {
            get
            {
                return this.descrizionePrezzoMedioField;
            }
            set
            {
                this.descrizionePrezzoMedioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PrezzoMedio")]
        public PrezzoMedio[] PrezzoMedio
        {
            get
            {
                return this.prezzoMedioField;
            }
            set
            {
                this.prezzoMedioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Commissionato")]
        public Commissionato[] Commissionato
        {
            get
            {
                return this.commissionatoField;
            }
            set
            {
                this.commissionatoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class KPIAgenzie
    {

        private string descrizioneCommissionatoField;

        private string descrizionePrezzoMedioField;

        private PrezzoMedio[] prezzoMedioField;

        private Commissionato[] commissionatoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DescrizioneCommissionato
        {
            get
            {
                return this.descrizioneCommissionatoField;
            }
            set
            {
                this.descrizioneCommissionatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DescrizionePrezzoMedio
        {
            get
            {
                return this.descrizionePrezzoMedioField;
            }
            set
            {
                this.descrizionePrezzoMedioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PrezzoMedio")]
        public PrezzoMedio[] PrezzoMedio
        {
            get
            {
                return this.prezzoMedioField;
            }
            set
            {
                this.prezzoMedioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Commissionato")]
        public Commissionato[] Commissionato
        {
            get
            {
                return this.commissionatoField;
            }
            set
            {
                this.commissionatoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Commissionato", typeof(Commissionato))]
        [System.Xml.Serialization.XmlElementAttribute("KPI", typeof(KPI))]
        [System.Xml.Serialization.XmlElementAttribute("PrezzoMedio", typeof(PrezzoMedio))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}